CREATE DATABASE BD_MATERIALES
GO

USE[BD_MATERIALES]

GO
CREATE TABLE TB_DATOS(
	[ID] INT NOT NULL IDENTITY(1,1),
	[BUILDINGMACHINE] [varchar](25) NULL,
	[BUILDINGSIZE] [varchar](25) NULL,
	[VERIFYDATETIME] [datetime2] NULL,
	[BSDATESHIFT] [int] NULL,
	[BUILDINGLOTNO] [int] NULL,
	[BUILDER1] [int] NULL,
	[MATERIALBARCODENO] [varchar](25) NULL,
	[PARTIID] [int] NULL,
	[PARTNAME] [varchar](25) NULL,
	[PARTNUMBER] [varchar](25) NULL,
	[DATEPRODUCED] [datetime2] NULL,
	[REMAIN] [numeric](10, 5) NULL,
	[MACHINEPRODUCED] [varchar](10) NULL,
	[MACHINENAME] [nvarchar](50) NULL
	CONSTRAINT PK_DATOS PRIMARY KEY(ID)
	) 

GO


CREATE PROCEDURE SP_ACTUALIZAR_DATOS_SEGUMIENTO_MATERIALES
AS BEGIN

CREATE TABLE [dbo].TB_DATOS_AUX(
	[ID] INT NOT NULL IDENTITY(1,1),
	[BUILDINGMACHINE] [varchar](25) NULL,
	[BUILDINGSIZE] [varchar](25) NULL,
	[VERIFYDATETIME] [datetime2] NULL,
	[BSDATESHIFT] [int] NULL,
	[BUILDINGLOTNO] [int] NULL,
	[BUILDER1] [int] NULL,
	[MATERIALBARCODENO] [varchar](25) NULL,
	[PARTIID] [int] NULL,
	[PARTNAME] [varchar](25) NULL,
	[PARTNUMBER] [varchar](25) NULL,
	[DATEPRODUCED] [datetime2] NULL,
	[REMAIN] [numeric](10, 5) NULL,
	[MACHINEPRODUCED] [varchar](10) NULL,
	[MACHINENAME] [nvarchar](50) NULL
	CONSTRAINT PK_DATOS_AUX PRIMARY KEY(ID),
)

INSERT INTO TB_DATOS_AUX SELECT * FROM OPENQUERY(BOSS2, 'SELECT BI.BUILDINGMACHINE,BI.BUILDINGSIZE,BI.DATETIME AS VERIFYDATETIME,BI.BSDATESHIFT,BI.BUILDINGLOTNO,BI.BUILDER1,BI.MATERIALBARCODENO,BI.ID2 AS PARTIID , BI.PARTNAME, 
MI.PARTNUMBER,MI.DATEPRODUCED, MI.REMAIN , MI.MACHINEID AS MACHINEPRODUCED,
MM.MACHINENAMELONG AS MACHINENAME
FROM Z_BUILDINGORIGINALHISTORY BI
LEFT JOIN Z_MATERIALINVENTORY MI ON BI.MATERIALBARCODENO=MI.CARTNUMBER
LEFT JOIN Z_MATERIALMACHINEMASTER MM ON MI.MACHINEID=MM.MACHINEID
WHERE BI.ID1=''04'' AND BI.BARCODECHECKRESULT=''1'' AND BI.PARTNAME<>''            '' AND DATETIME > add_months( sysdate, -1 )
ORDER BY DATETIME ASC
')

DROP TABLE TB_DATOS
EXEC SP_RENAME 'TB_DATOS_AUX', 'TB_DATOS'
EXEC sp_rename @objname = N'[TB_DATOS].[PK_DATOS_AUX]', @newname = N'PK_DATOS'



END

GO

CREATE PROCEDURE SP_TRAER_DATOS
AS BEGIN
SELECT TOP 5000 *
  FROM [BD_MATERIALES].[dbo].[TB_DATOS]
END

GO

CREATE PROCEDURE SP_TRAER_DATOS_FECHAS

@strStart DATE,
@strFin DATE

AS BEGIN
--SELECT @strStart
--SELECT @strFin
--SELECT * FROM TB_DATOS
--SELECT CONVERT(datetime,@strStart)
--SELECT CONVERT(datetime,@strFin)
SELECT *
  FROM [BD_MATERIALES].[dbo].[TB_DATOS]
	WHERE VERIFYDATETIME BETWEEN CONVERT(datetime,@strStart) AND CONVERT(datetime,@strFin)
END


GO

CREATE PROCEDURE SP_HORA_ULT_JOB_CORRECTO
AS BEGIN

	--Convierto a string
	SELECT convert(varchar(25),
						--Traigo ultima fecha de job exitoso
						(SELECT TOP 1  dateadd(second, (run_time/10000*3600) + (((run_time%10000-run_time%100)/100)*60) + (run_time%100), convert(datetime,cast(nullif(run_date,0) as nvarchar(10)))) as [last_run_datetime]
						FROM [msdb].[dbo].[sysjobhistory] JH
						JOIN [msdb].[dbo].[sysjobs] J
						ON JH.job_id= J.job_id
						WHERE J.name='ActualizaDatosSeguimientoMat' AND message like 'The job succeeded.%' 
						ORDER BY last_run_datetime DESC)
					,120) 

END