//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_MATERIALESEntities : DbContext
    {
        public BD_MATERIALESEntities()
            : base("name=BD_MATERIALESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_DATOS> TB_DATOS { get; set; }
    
        public virtual ObjectResult<SP_TRAER_DATOS_Result> SP_TRAER_DATOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TRAER_DATOS_Result>("SP_TRAER_DATOS");
        }
    
        public virtual ObjectResult<SP_TRAER_DATOS_FECHAS_Result> SP_TRAER_DATOS_FECHAS(Nullable<System.DateTime> strStart, Nullable<System.DateTime> strFin)
        {
            var strStartParameter = strStart.HasValue ?
                new ObjectParameter("strStart", strStart) :
                new ObjectParameter("strStart", typeof(System.DateTime));
    
            var strFinParameter = strFin.HasValue ?
                new ObjectParameter("strFin", strFin) :
                new ObjectParameter("strFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_TRAER_DATOS_FECHAS_Result>("SP_TRAER_DATOS_FECHAS", strStartParameter, strFinParameter);
        }
    }
}
